### ISSUE TITLE
Data preprocess issue

### ISSUE THREAD

**Issue by DuckYellowPP** [Ethan00Si/Instrumental-variables-for-recommendation#1]
Dear Ethan00Si,

I confused that how to generate file "ID2idx.json","news_all.tsv","news_data.tsv" during data preprocess stage.

Maybe you are thinking about MIND's license issue, but it's not a violation to publish code that handles datasets.

I would appreciate it if you could provide further data processing code or provide a more detailed data processing tutorial.

Thank you for your Outstanding work. Looking forward to your reply!

**Comment by Ethan00Si** [comment]
Hi!
Thanks for your suggestion. Due to concerns for [MSR License](https://github.com/msnews/MIND/blob/master/MSR%20License_Data.pdf), I have no right to distribute the MIND dataset.

Sorry that current codes don't cover all intricacies of the process.

Existing pre-processing codes show our methods to generate the queries and how to generate embeddings.

You can refer this code to process data on your own. 

Nowadays, I'm busy with my internship and research work. For better usage, I will provide more detailed data codes in future.

**Comment by Ethan00Si** [comment]
Hi :wave:！

I have updated data preprocessing codes.

I provide a more detailed  Jupyter Notebook to filter and split data.
